[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = [
  "dotnet restore EnterpriseGradeInventoryManagementSystem.sln",
  "dotnet publish EnterpriseGradeInventoryManagementSystem.sln -c Release -o out --no-restore"
]

[phases.start]
cmd = "dotnet out/EnterpriseGradeInventoryAPI.dll"

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:${PORT}"
